version: '2'
services:
  web:
    image: web
    ports:
     - "@webport:80"
    volumes:
     - ./jexus:/usr/jexus
     - ./www:/var/www/default    
    command: /bin/bash /usr/jexus/start.sh
    networks:
      app_net:
        ipv4_address: 10.10.@appid.3
    depends_on:
     - db
  db:
    image: db
    ports:
     - "@dbport:5432"
    volumes:
     - ./data:/var/lib/postgresql/data
     - ./www/app_data/dbbak:/var/dbbak
    networks:
      app_net:
        ipv4_address: 10.10.@appid.2
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.@appid.1/24
